{{- if (and (eq .Values.db.connectionString "") (not .Values.localTesting)) }}
  {{- if ne .Values.cloudProvider "local_trident"}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
  {{- end }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  {{- if and (ne .Values.cloudProvider "local_trident") (ne .Values.trident.storageClassName "")}}
  storageClassName: {{ .Values.trident.storageClassName }}
  {{- end }}
{{- end }}