{{- if eq .Values.openshiftCompatibleMode true}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: genai-manager
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: genai-manager-binding-privileged-scc
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: genai-manager
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
{{- end }}