apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-toolkit-ui
  labels:
    app: genai-toolkit-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-toolkit-ui
  template:
    metadata:
      labels:
        app: genai-toolkit-ui
    spec:
      initContainers:
        - name: wait-for-auth
          image: busybox
          command: ['sh', '-c', 'until wget -qO- http://genai-toolkit-rag-api.{{ .Release.Namespace }}.svc.cluster.local:8002/health; do echo waiting for genai-toolkit-rag-api; sleep 2; done']
      containers:
        - name: genai-toolkit-ui
          {{- if not .Values.localTesting }}
          image: {{ .Values.dockerRegistry }}genai-toolkit-ui:{{ .Chart.Version }}
          {{- else }}
          image: {{ .Values.dockerRegistry }}genai-toolkit-ui:{{ .Values.devTag }}
          {{- end }}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: rsa-keys-volume
              mountPath: /keys/public
      volumes:
        - name: rsa-keys-volume
          secret:
            secretName: rsa-keys
            items:
              - key: public_key.rsa
                path: public_key.rsa
---
apiVersion: v1
kind: Service
metadata:
  name: genai-toolkit-ui
  labels:
    app: genai-toolkit-ui
spec:
  selector:
    app: genai-toolkit-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000